# Generated by Django 4.2 on 2023-04-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='my menu', help_text='maximum 100 characters', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menubranch',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave the field blank if attached to the menu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menubranch', verbose_name='Parent branch'),
        ),
    ]
